name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.3

environment:
  sdk: ^3.5.4
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path: ^1.9.0
  pointer_interceptor: 0.10.1+2
  uuid: ^3.0.7
  webview_flutter: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
